### ISSUE TITLE
 java.security.ProviderException: Failed to load generated key pair from keystore

### ISSUE THREAD

**Issue by mishragashish** [Kommunicate-io/Kommunicate-Android-Chat-SDK#164]
Getting this issue when open chatbot first time in app in some devices

    java.security.ProviderException: Failed to load generated key pair from keystore
        at android.security.keystore.AndroidKeyStoreKeyPairGeneratorSpi.loadKeystoreKeyPair(AndroidKeyStoreKeyPairGeneratorSpi.java:531)
        at android.security.keystore.AndroidKeyStoreKeyPairGeneratorSpi.generateKeyPair(AndroidKeyStoreKeyPairGeneratorSpi.java:473)
        at java.security.KeyPairGenerator$Delegate.generateKeyPair(KeyPairGenerator.java:727)
        at java.security.KeyPairGenerator.genKeyPair(KeyPairGenerator.java:497)
        at com.applozic.mobicommons.encryption.SecurityUtils.generateRSAKeyPair(SecurityUtils.java:92)
        at com.applozic.mobicommons.encryption.SecurityUtils.getRSAKeyPair(SecurityUtils.java:111)
        at com.applozic.mobicommons.data.SecureSharedPreferences.<init>(SecureSharedPreferences.java:38)
        at com.applozic.mobicommons.data.AlPrefSettings.<init>(AlPrefSettings.java:31)
        at com.applozic.mobicommons.data.AlPrefSettings.getInstance(AlPrefSettings.java:36)
        at com.applozic.mobicomkit.Applozic.getApplicationKey(Applozic.java:85)
        at io.kommunicate.Kommunicate.init(Kommunicate.java:81)
        at com.cancan.Views.Fragments.HomeFragment.openConversation(HomeFragment.kt:102)
        at com.cancan.Views.Fragments.HomeFragment.onClick(HomeFragment.kt:96)
        at android.view.View.performClick(View.java:7448)
        at android.view.View.performClickInternal(View.java:7425)
        at android.view.View.access$3600(View.java:810)
        at android.view.View$PerformClick.run(View.java:28305)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
     Caused by: java.security.UnrecoverableKeyException: Failed to obtain information about key
        at android.security.keystore.AndroidKeyStoreProvider.getKeyCharacteristics(AndroidKeyStoreProvider.java:248)
        at android.security.keystore.AndroidKeyStoreProvider.loadAndroidKeyStoreKeyPairFromKeystore(AndroidKeyStoreProvider.java:316)
        at android.security.keystore.AndroidKeyStoreKeyPairGeneratorSpi.loadKeystoreKeyPair(AndroidKeyStoreKeyPairGeneratorSpi.java:522)
        at android.security.keystore.AndroidKeyStoreKeyPairGeneratorSpi.generateKeyPair(AndroidKeyStoreKeyPairGeneratorSpi.java:473) 
        at java.security.KeyPairGenerator$Delegate.generateKeyPair(KeyPairGenerator.java:727) 
        at java.security.KeyPairGenerator.genKeyPair(KeyPairGenerator.java:497) 
        at com.applozic.mobicommons.encryption.SecurityUtils.generateRSAKeyPair(SecurityUtils.java:92) 
        at com.applozic.mobicommons.encryption.SecurityUtils.getRSAKeyPair(SecurityUtils.java:111) 
        at com.applozic.mobicommons.data.SecureSharedPreferences.<init>(SecureSharedPreferences.java:38) 
        at com.applozic.mobicommons.data.AlPrefSettings.<init>(AlPrefSettings.java:31) 
        at com.applozic.mobicommons.data.AlPrefSettings.getInstance(AlPrefSettings.java:36) 
        at com.applozic.mobicomkit.Applozic.getApplicationKey(Applozic.java:85) 
        at io.kommunicate.Kommunicate.init(Kommunicate.java:81) 
        at com.cancan.Views.Fragments.HomeFragment.openConversation(HomeFragment.kt:102) 
        at com.cancan.Views.Fragments.HomeFragment.onClick(HomeFragment.kt:96) 
        at android.view.View.performClick(View.java:7448) 
        at android.view.View.performClickInternal(View.java:7425) 
        at android.view.View.access$3600(View.java:810) 
        at android.view.View$PerformClick.run(View.java:28305) 
        at android.os.Handler.handleCallback(Handler.java:938) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:223) 
        at android.app.ActivityThread.main(ActivityThread.java:7656) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947) 
     Caused by: android.security.KeyStoreException: Key not found
        at android.security.KeyStore.getKeyStoreException(KeyStore.java:1281)
        at android.security.keystore.AndroidKeyStoreProvider.getKeyCharacteristics(AndroidKeyStoreProvider.java:250)
        at android.security.keystore.AndroidKeyStoreProvider.loadAndroidKeyStoreKeyPairFromKeystore(AndroidKeyStoreProvider.java:316) 
        at android.security.keystore.AndroidKeyStoreKeyPairGeneratorSpi.loadKeystoreKeyPair(AndroidKeyStoreKeyPairGeneratorSpi.java:522) 
        at android.security.keystore.AndroidKeyStoreKeyPairGeneratorSpi.generateKeyPair(AndroidKeyStoreKeyPairGeneratorSpi.java:473) 
        at java.security.KeyPairGenerator$Delegate.generateKeyPair(KeyPairGenerator.java:727) 
        at java.security.KeyPairGenerator.genKeyPair(KeyPairGenerator.java:497) 
        at com.applozic.mobicommons.encryption.SecurityUtils.generateRSAKeyPair(SecurityUtils.java:92) 
        at com.applozic.mobicommons.encryption.SecurityUtils.getRSAKeyPair(SecurityUtils.java:111) 
        at com.applozic.mobicommons.data.SecureSharedPreferences.<init>(SecureSharedPreferences.java:38) 
        at com.applozic.mobicommons.data.AlPrefSettings.<init>(AlPrefSettings.java:31) 
        at com.applozic.mobicommons.data.AlPrefSettings.getInstance(AlPrefSettings.java:36) 
        at com.applozic.mobicomkit.Applozic.getApplicationKey(Applozic.java:85) 
        at io.kommunicate.Kommunicate.init(Kommunicate.java:81) 
        at com.cancan.Views.Fragments.HomeFragment.openConversation(HomeFragment.kt:102) 
        at com.cancan.Views.Fragments.HomeFragment.onClick(HomeFragment.kt:96) 
        at android.view.View.performClick(View.java:7448) 
        at android.view.View.performClickInternal(View.java:7425) 
        at android.view.View.access$3600(View.java:810) 
        at android.view.View$PerformClick.run(View.java:28305) 
        at android.os.Handler.handleCallback(Handler.java:938) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:223) 
        at android.app.ActivityThread.main(ActivityThread.java:7656) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

**Comment by mishragashish** [comment]
Getting this issue when open chatbot first time in app in some devices

**Comment by Samir1810** [comment]
Please let us know if you're still having the issue? Mention the kommunicate sdk version you're using.
